packages:
  - apps/*
  - packages/*
  - apps/workers/*

catalog:
  '@types/node': ^22.19.1
  dotenv: ^17.2.3
  tsdown: ^0.15.12
  typescript: ^5.9.3
  zod: 4.1.12

onlyBuiltDependencies:
  - esbuild
  - sharp
